### ISSUE TITLE
Disabling the plot display in gplots's heatmap.2

### ISSUE THREAD

**Issue by ndrubins** [talgalili/gplots#12]
Hi,

I'm using the `heatmap.2` function from R command line running on a linux machine with no X11 display and I'm getting this error:

```
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
  unable to start device X11cairo
In addition: Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''
```

Is there a way to disable the default plotting so that I don't get this error?

Thanks

**Comment by talgalili** [comment]
Hey,
What's the purpose? To get the object but without the plotting? How come?

**Comment by ndrubins** [comment]
Hi Tal,

Yes, I'm running it from the command line because there are several steps after the call to `heatmap.2` that are resource intensive and I need to use a high performance compute cluster node, which can only run R from the command line.

I guess I can first call `heatmap.2` from RStudio, save its output, and then switch to the command line, but was wondering if there's a way to disable the plotting option in 'heatmap.2`, which would save me that.

Thanks

**Comment by talgalili** [comment]
You can use
pdf(filename) #or png()
Call heatmap.2
dev.off()
Continue your intense code.


Alternatively you can use
p <- heatmaply::ggheatmap()
Code
Then run
p


WDYT?

**Comment by ndrubins** [comment]
First solution does the trick.

Thanks!
